### ISSUE TITLE
Unknown Symbol with config file

### ISSUE THREAD

**Issue by mvoellmy** [obxyann/Sublime-Uncrustify#10]
Hi,

Thanks for developing and publishing this plugin. I can see it being very helpful to our development. 

I am trying to use the plugin on Ubuntu 18.04 with the following config file:

https://github.com/ament/ament_lint/blob/master/ament_uncrustify/ament_uncrustify/configuration/ament_code_style.cfg

I changed my user settings to point to the uncrustify executable and to the config file as follows:

`  "uncrustify_executable" : "/usr/bin/uncrustify", `

`  "uncrustify_config" : "/home/freki/rover_wss/ros2_ws/src/simple_rover_locomotion/ament_code_style.cfg",`

Unfortunately, I'm receiving the following error:

![image](https://user-images.githubusercontent.com/10925797/79874231-61855200-83e8-11ea-9190-420910af5f91.png)

Using uncrustify from the command line with the same config file does not throw an error and works flawless.

`uncrustify -f src/simple_rover_locomotion.cpp -o output.cpp -c ament_code_style.cfg`

Using your plugin with a simpler config file also worked.

Do you have any idea where the issue might be?

Thanks a lot,

Miro

**Comment by obxyann** [comment]
hi~ this plugin just run below command with stdin/stdout source content when you run format source

`Uncrustify.py line 285: command = [program, "-l", lang, "-c", config]`

for your config it will be

`/usr/bin/uncrustify -l CPP -c /home/freki/rover_wss/ros2_ws/src/simple_rover_locomotion/ament_code_style.cfg`

You can check sublime's console to see the command log which 
`Uncrustify.py line 291: print("> " + running + " ...")`

I saw your log, the uncrustify already called and ament_code_style.cfg had assigned. but uncrustify return errors about bad config, it should because the uncrustify problem because this plugin just pass the path of config as param to uncrustify, plugin didn't mod/load config...

if you google 'uncrustify return unknown symbol' someone has problem like this finally because the old uncrustify (maybe the file format of  ament_code_style.cfg?)

please use 

`/usr/bin/uncrustify -l CPP -c /home/freki/rover_wss/ros2_ws/src/simple_rover_locomotion/ament_code_style.cfg -f src/simple_rover_locomotion.cpp -o output.cpp`

test again

(Note: and please check sublime's console about sublime-uncrustify running command which uncrustify it called)

**Comment by mvoellmy** [comment]
Hi Obxyann!

Thanks, I discovered that I had multiple versions of `uncrustify `installed.
With running `whereis uncrustify` I found that ROS installed a `uncrustify` here: `/opt/ros/eloquent/bin/uncrustify`. Changing the config to that made it work in sublime!

Thanks for the pointers!
