### ISSUE TITLE
Execute command silently

### ISSUE THREAD

**Issue by JEsword** [obxyann/Sublime-Uncrustify#2]
There's always a console window flash when I do format on Win10.
In Uncrustify.py, if I add a parameter "shell = True" for line 290:

```
        proc = subprocess.Popen(command, \
               stdin = subprocess.PIPE, stdout = subprocess.PIPE, stderr = subprocess.PIPE, shell = True)
```

Then it will be executed silently without any console window display. But I'm not familiar with Python enough and not sure if it works for other platforms.

**Comment by obxyann** [comment]
Yes, I got a Win10 and tested, the console appearing in every action.
As your adding 'parameter "shell = True"', it seems not a best solution, because it will open the Shell (cmd.exe in Windows) as a process to run original command as arguments of shell. what real hided the console is when set shell=true it will [configure the STARTUPINFO](https://hg.python.org/cpython/file/ab05e7dd2788/Lib/subprocess.py#l918). so i just configure the STARTUPINFO and also work.
